[mypy]
python_version = 3.11
plugins = mypy_django_plugin.main
warn_return_any = true
warn_unused_configs = true
show_error_codes = true

[mypy.plugins.django-stubs]
django_settings_module = "mail_client.settings"

[mypy-celery]
ignore_missing_imports = True
[mypy-celery.*]
ignore_missing_imports = True
[mypy-redis]
ignore_missing_imports = True
[mypy-redis.*]
ignore_missing_imports = True
[mypy-sqlalchemy]
ignore_missing_imports = True
[mypy-sqlalchemy.*]
ignore_missing_imports = True
[mypy-cryptography]
ignore_missing_imports = True
[mypy-cryptography.*]
ignore_missing_imports = True
[mypy-django_redis]
ignore_missing_imports = True

[mypy]
disable_error_code = var-annotated