# Generated by Django 5.2.14 on 2026-05-10 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('encrypted_password', models.BinaryField()),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=465)),
                ('use_ssl', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('message_id', models.CharField(db_index=True, max_length=255)),
                ('subject', models.CharField(max_length=1024)),
                ('sender', models.CharField(max_length=255)),
                ('recipients', models.JSONField(default=list)),
                ('date', models.DateTimeField()),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('folder', models.CharField(default='INBOX', max_length=100)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.mailaccount')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('account', 'uid')},
            },
        ),
    ]
