# Generated by Django 4.2.30 on 2026-05-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'ordering': ['-date'], 'verbose_name': 'Письмо', 'verbose_name_plural': 'Письма'},
        ),
        migrations.AlterModelOptions(
            name='mailaccount',
            options={'verbose_name': 'Почтовый аккаунт', 'verbose_name_plural': 'Почтовые аккаунты'},
        ),
    ]
